# Generated by Django 3.2.19 on 2023-05-08 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230508_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'verbose_name': 'публикация', 'verbose_name_plural': 'публикации'},
        ),
        migrations.AlterModelOptions(
            name='publicationcategory',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='description',
            new_name='text',
        ),
    ]
