# Generated by Django 3.2.19 on 2023-06-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='planet',
            field=models.CharField(default='a', max_length=256),
            preserve_default=False,
        ),
    ]
